# Generated by Django 3.2.9 on 2021-12-22 16:21

import coupon.models
import datetime
from django.db import migrations, models
import localflavor.br.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', localflavor.br.models.BRCPFField(max_length=14)),
                ('target', localflavor.br.models.BRCPFField(max_length=14)),
                ('coupon', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateField(default=datetime.date(2021, 12, 22))),
                ('expires', models.DateField(default=coupon.models.valid_to)),
            ],
        ),
    ]
