# Generated by Django 3.2.9 on 2021-12-23 14:55

import datetime
import django.core.validators
from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='created',
            field=models.DateField(default=datetime.date(2021, 12, 23)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='source',
            field=localflavor.br.models.BRCPFField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^.{11}$')]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='target',
            field=localflavor.br.models.BRCPFField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^.{11}$')]),
        ),
    ]
