# Generated by Django 3.2.9 on 2021-12-22 16:21

from django.db import migrations, models
import localflavor.br.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('cpf', localflavor.br.models.BRCPFField(help_text='Formato: 00011122233', max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Formato DDD + Número', max_length=128, region='BR', verbose_name='Telefone')),
                ('address', models.CharField(max_length=50, verbose_name='Endereço')),
                ('zipcode', localflavor.br.models.BRPostalCodeField(help_text='Formato 00000-000', max_length=9, verbose_name='CEP')),
                ('points', models.PositiveIntegerField(default=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
