# Generated by Django 3.2.9 on 2021-12-23 14:55

import django.core.validators
from django.db import migrations, models
import localflavor.br.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cpf',
            field=localflavor.br.models.BRCPFField(help_text='Formato: 00011122233', max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^.{11}$')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Formato DDD + Número', max_length=128, region='BR', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='zipcode',
            field=localflavor.br.models.BRPostalCodeField(blank=True, help_text='Formato 00000-000', max_length=9, verbose_name='CEP'),
        ),
    ]
