# Generated by Django 3.2.9 on 2021-12-17 13:22

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cpf',
            field=localflavor.br.models.BRCPFField(help_text='Formato: 00011122233', max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermember',
            name='cpf',
            field=localflavor.br.models.BRCPFField(help_text='Formato: 00011122233', max_length=14, primary_key=True, serialize=False),
        ),
    ]
