# Generated by Django 3.2.9 on 2021-12-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20211217_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterMember',
            new_name='Register',
        ),
    ]
