# Generated by Django 3.2.9 on 2021-12-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_rename_registermember_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.register'),
            preserve_default=False,
        ),
    ]
