# Generated by Django 3.2.9 on 2021-12-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_member_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.register'),
        ),
    ]
