# Generated by Django 3.2.9 on 2021-12-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_member_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fk',
        ),
    ]
