# Generated by Django 3.2.9 on 2021-12-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='today',
            new_name='hoje',
        ),
    ]
